### PR TITLE
fix: movies with unavailable posters will be shown in the last row

### LINKED ISSUE #665: [Bug]: Movies with missing posters displayed in search results
### What happened?

Searching for movies sometimes leads to entries with missing posters. Clicking on these movies often generates a “result not found” message. This creates a bad user experience.

### What browsers are you seeing the problem on?

Firefox

### Steps to reproduce?

1. Go to the search page
2. Search nemo (You found there were two movies that have no poster)
3. click anyone (When you click on those, the result is 'not found')

### Other relevant information

image
image

### PR DESCRIPTION
**Pull request by ashudevcodes**
This pull request resolves #665 

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

# All movies with unavailable posters will be shown in the last row
image
image

### CODE REVIEW

File: src/backend/metadata/search.ts [hunk 1]
```diff
@@ -24,6 +24,17 @@ export async function searchForMedia(query: MWQuery): Promise<MediaItem[]> {
...
+  results.sort((a, b) => {
+    if (a.poster === undefined) {
+      return 1;
+    }
+    if (b.poster === undefined) {
+      return -1;
+    }
+    return 0;
+  });
+
```
Comment (qtchaos) [inline src/backend/metadata/search.ts:36]: pnpm lint:fix

File: src/backend/metadata/search.ts [hunk 2]
```diff
@@ -24,6 +24,17 @@ export async function searchForMedia(query: MWQuery): Promise<MediaItem[]> {
...
 
-  cache.set(query, results, 3600); // cache results for 1 hour
+  results.sort((a, b) => {
+    if (a.poster === undefined) {
+      return 1;
+    }
+    if (b.poster === undefined) {
+      return -1;
+    }
+    return 0;
```
Comment (mrjvs) [inline src/backend/metadata/search.ts:34]: This destroys the order that the undefined posts come in.
Especially since the sequence of when the elements get compared is undefined behaviour, so sorting would come out randomized in theory.

This fix probably can't be done with a sort(), so I recommend making two seperate arrays (with poster and without poster) using filter(). then concatinating them.

**Review by mrjvs — CHANGES_REQUESTED** [review]

File: src/backend/metadata/search.ts (hunk 2 above)
Comment (binaryoverload) [reply src/backend/metadata/search.ts:34]: Sorting shouldn't come out as randomised since Array.sort is a stable sort surely?

Comment (binaryoverload) [reply src/backend/metadata/search.ts:34]: After a discussion internally, please proceed with JVS's suggestion of filtering @ashudevcodes

File: src/backend/metadata/search.ts [hunk 3]
```diff
@@ -24,6 +24,12 @@ export async function searchForMedia(query: MWQuery): Promise<MediaItem[]> {
     return formatTMDBMetaToMediaItem(formattedResult);
   });
 
-  cache.set(query, results, 3600); // cache results for 1 hour
-  return results;
+  const movieWithposters = results.filter((movie) => movie.poster);
+  const movieWithoutposters = results.filter((movie) => !movie.poster);
+
+  const sortedresult = movieWithposters.concat(movieWithoutposters);
```
Comment (binaryoverload) [inline src/backend/metadata/search.ts:30]: Minor stylistic nit-pick

```suggestion
  const movieWithPosters = results.filter((movie) => movie.poster);
  const movieWithoutPosters = results.filter((movie) => !movie.poster);

  const sortedresult = movieWithPosters.concat(movieWithoutPosters);
```

**Review by binaryoverload — CHANGES_REQUESTED** [review]

**Review by mrjvs — APPROVED** [review]
