### PR TITLE
Fixed next episode button not loading new season

### LINKED ISSUE #1049: [Feature] - Show a "Next Season" button when at the end of a TV season
### What happened?

when at the last episode in the season, even if there is another season there is no NextEpisodeButton because of his the nextEp var is set

### What browsers are you seeing the problem on?

Microsoft Edge

### Steps to reproduce?

1. go to a show and click on it
2. go to the last episode of the season
3. fast forward to ~10 seconds before episode depletion 
4. don’t see a button for the next episode even if there’s another season

### Other relevant information

_No response_

### PR DESCRIPTION
**Pull request by dro-1**
This pull request resolves #1049.
The next episode button was not showing when the last episode of a season was reached. It is now showing and loads said episode when clicked.

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

### CODE REVIEW

File: src/components/player/atoms/NextEpisodeButton.tsx [hunk 1]
```diff
@@ -47,17 +52,61 @@ export function NextEpisodeButton(props: {
...
+    meta?.tmdbId ?? "",
+    meta?.season?.tmdbId ?? "",
+  );
   const { setDirectMeta } = usePlayerMeta();
   const hideNextEpisodeButton = usePlayerStore((s) => s.hideNextEpisodeButton);
   const metaType = usePlayerStore((s) => s.meta?.type);
   const time = usePlayerStore((s) => s.progress.time);
   const showingState = shouldShowNextEpisodeButton(time, duration);
   const status = usePlayerStore((s) => s.status);
+  const [nextSeason, setNextSeason] = useState<MWSeasonMeta>();
```
Comment (JorrinKievit) [inline src/components/player/atoms/NextEpisodeButton.tsx:65]: I dont think we need this state. a simple local variable 
 ```
const nextSeason = seasons?.find(
    (season) => season.number === (meta?.season?.number ?? 0) + 1,
  );
```

would suffice

File: src/components/player/atoms/NextEpisodeButton.tsx [hunk 2]
```diff
@@ -47,17 +52,61 @@ export function NextEpisodeButton(props: {
   const duration = usePlayerStore((s) => s.progress.duration);
   const isHidden = usePlayerStore((s) => s.interface.hideNextEpisodeBtn);
   const meta = usePlayerStore((s) => s.meta);
+  const [_, seasons] = useSeasonData(
```
Comment (JorrinKievit) [inline src/components/player/atoms/NextEpisodeButton.tsx:55]: This does not seem necessary if the current episode is not the last episode. Can we make sure this is only called when that is the case? This way we can prevent an unneeded call

File: src/components/player/atoms/NextEpisodeButton.tsx [hunk 3]
```diff
@@ -47,17 +52,61 @@ export function NextEpisodeButton(props: {
...
+  useEffect(() => {
+    if (seasons) {
+      const next = seasons.find(
+        (season) => season.number === (meta?.season?.number ?? 0) + 1,
+      );
+      setNextSeason(next);
+    }
+  }, [meta?.season?.number, seasons]);
+
+  useEffect(() => {
```
Comment (JorrinKievit) [inline src/components/player/atoms/NextEpisodeButton.tsx:87]: We could use the useAsync hook here. Then we can also get rid of the `nextSeasonEpisodes` local state. We also do not need all the episodes, so only returning the first one from the useAsync hook would suffice.

File: src/components/player/atoms/NextEpisodeButton.tsx [hunk 4]
```diff
@@ -47,17 +52,61 @@ export function NextEpisodeButton(props: {
...
+      title: string;
+      tmdbId: string;
+    }[]
+  >([]);
   const setShouldStartFromBeginning = usePlayerStore(
     (s) => s.setShouldStartFromBeginning,
   );
   const updateItem = useProgressStore((s) => s.updateItem);
 
+  useEffect(() => {
```
Comment (JorrinKievit) [inline src/components/player/atoms/NextEpisodeButton.tsx:78]: We can remove this when we use the local nextSeason variable

**Review by JorrinKievit — CHANGES_REQUESTED** [review]

**Review by JorrinKievit — DISMISSED** [review]
Also the button should show "Next season" when its on the last episode, and there is a next season

**Comment by dro-1** [comment]
Made the requested changes @JorrinKievit . 
Awaiting review.

File: src/components/player/atoms/NextEpisodeButton.tsx [hunk 5]
```diff
@@ -121,7 +190,10 @@ export function NextEpisodeButton(props: {
           className="bg-buttons-primary hover:bg-buttons-primaryHover text-buttons-primaryText flex justify-center items-center"
         >
           <Icon className="text-xl mr-1" icon={Icons.SKIP_EPISODE} />
-          {t("player.nextEpisode.next")}
+          {isLastEpisode && nextEp
+            ? t("player.nextEpisode.nextSeason")
+            : t("player.nextEpisode.next")}
+          {}
```
Comment (qtchaos) [inline src/components/player/atoms/NextEpisodeButton.tsx:196]: stray braces?

**Review by qtchaos — CHANGES_REQUESTED** [review]

File: src/components/player/atoms/NextEpisodeButton.tsx [hunk 6]
```diff
@@ -39,6 +44,45 @@ function Button(props: {
...
+
+      const nextSeasonEpisodes = data?.meta?.seasonData?.episodes
+        .filter((episode) => hasAired(episode.air_date))
+        .map((episode) => ({
+          number: episode.number,
+          title: episode.title,
+          tmdbId: episode.id,
+        }));
+
+      if (nextSeasonEpisodes.length) return nextSeasonEpisodes[0];
```
Comment (binaryoverload) [inline src/components/player/atoms/NextEpisodeButton.tsx:80]: I generally dislike falsy checks, they are pretty unclear when scanning code

```suggestion
      if (nextSeasonEpisodes.length > 0) return nextSeasonEpisodes[0];
```

**Review by binaryoverload — CHANGES_REQUESTED** [review]

File: src/components/player/atoms/NextEpisodeButton.tsx (hunk 5 above)
Comment (dro-1) [reply src/components/player/atoms/NextEpisodeButton.tsx:196]: oh yeah, they definitely are. I'll fix them right away.
do you think it might be reasonable to add that rule to the linter so we catch it next time?

Comment (qtchaos) [reply src/components/player/atoms/NextEpisodeButton.tsx:196]: If there's a rule for that then I wouldn't be against it

**Comment by dro-1** [comment]
Fixed the issues and squashed the commits into one.
I didn't find any linter rule for empty braces so I left that.

**Comment by binaryoverload** [comment]
@dro-1 FYI, generally, it's bad practice to rebase while your PR is open for review, as it makes it harder for reviewers to see what you've done 

I'll test the PR then LGTM

**Review by binaryoverload — APPROVED** [review]

**Comment by dro-1** [comment]
sorry about that @binaryoverload , I'll avoid it in future PRs.
what does LGTM mean 👀

**Comment by qtchaos** [comment]
> what does LGTM mean 👀

Looking good to me
