### PR TITLE
Language code fixes

### LINKED ISSUE #680: [Bug]: Wrong flag in pt-br translation
### What happened?

Recently, Brazilian Portuguese translation was added, but the flag that appears in the options menu is that of European Portuguese, which is a significantly different language.

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

Go to the language selector and check the flag

### Other relevant information

I have already implemented the solution; I just need permission to submit the pull request.

### PR DESCRIPTION
**Pull request by binaryoverload**
This pull request resolves #680

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

This changes our language utils to read the region from the language code - this means we only need to specify manual overrides for languages that either:
 a) have an incorrect region
 b) don't have a region in the language code (i.e. `zh-Hant`)

### CODE REVIEW

**Comment by mrjvs** [comment]
Ew, force push

File: src/utils/language.ts [hunk 1]
```diff
@@ -5,19 +5,11 @@ const languageOrder = ["en", "hi", "fr", "de", "nl", "pt"];
...
-  en: "us",
-  nl: "nl",
-  fr: "fr",
-  de: "de",
-  pt: "pt",
-  ar: "sa",
-  es: "es",
   zh: "cn",
-  ko: "kr",
-  ta: "lk",
```
Comment (mrjvs) [inline src/utils/language.ts:20]: Does this work? One of the issues that this mapping solved was that for example in NL. The Netherlands isn't the first country on the list of countries that speak the language, the first one would be Belgium since its earlier in alphabetical order.

The mapping wasn't just for stuff like scripts

**Review by mrjvs — CHANGES_REQUESTED** [review]

File: src/utils/language.ts (hunk 1 above)
Comment (binaryoverload) [reply src/utils/language.ts:20]: Yes it does because we have the default language codes which have Dutch as `nl-NL` - the `NL` being the region

Comment (binaryoverload) [reply src/utils/language.ts:20]: If we didn't have the default language codes you would be right, but because we have a mapping of language -> language with region then it works

Comment (mrjvs) [reply src/utils/language.ts:20]: Ah right, can you double check if subtitle flags still work then? I'm unsure if the default region mapping is applied there

Comment (binaryoverload) [reply src/utils/language.ts:20]: Fair point well made - they didn't (Because I forgot this logic was used there. I've updated the getCountryCodeForLocale method to use the populateLanguageCode method

**Review by mrjvs — APPROVED** [review]
