### PR TITLE
More bugfixes

### LINKED ISSUE #534: [Bug]: Tap to toggle on video controls doesn't go away after timeout
### What happened?

tapping shows video controls, it doesnt go away

### What browsers are you seeing the problem on?

Firefox

### Steps to reproduce?

1. have touch device
2. tap on video while playing
3. ...
4. controls dont go away after time

### Other relevant information

_No response_

### LINKED ISSUE #549: [Bug]: Blurry Posters.
### What happened?

```tsx
export function getMediaPoster(posterPath: string | null): string | undefined {
  if (posterPath) return `https://image.tmdb.org/t/p/w185/${posterPath}`;
}
``` 

changing 

https://image.tmdb.org/t/p/w185/${posterPath}

to 

https://image.tmdb.org/t/p/original/${posterPath}

makes the posters look a lot better, they otherwise look blurry.

Comparision: 

image

image

### What browsers are you seeing the problem on?

_No response_

### Steps to reproduce?

_No response_

### Other relevant information

_No response_

### LINKED ISSUE #574: [Bug]: Not Found is broken
### What happened?

The not-found state of the scrapers doesn't end the scraping process and doesn't show the "Not Found" screen - just sits in the provider status flow.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Steps to reproduce?

1. Go to media which isn't on any of the scrapers: https://movie-web.app/media/tmdb-tv-93544-top-boy/132226/1928153
2. Profit (See screenshot)

### Other relevant information

Example: https://movie-web.app/media/tmdb-tv-93544-top-boy/132226/1928153

image

### PR DESCRIPTION
**Pull request by mrjvs**
changes:
 - Fix popouts not working, not sure when this broke. Possibly when with FocusTrap package update
 - Fix touch controls never dissappearing, added a 3 second timeout after not doing anything.
 - Fix not found page never being shown
 - Fix details button not doing anything if there are no errors
 - Improved quality of poster urls (this won't update posters saved in user data, only new ones or search results)
 - Added more info the error details modal

closes #549 
closes #574 
closes #534

### CODE REVIEW

File: src/pages/parts/player/ScrapeErrorPart.tsx [hunk 1]
```diff
@@ -22,21 +24,21 @@ export interface ScrapeErrorPartProps {
...
   const error = useMemo(() => {
     const data = props.data;
-    const amountError = Object.values(data.sources).filter(
-      (v) => v.status === "failure",
-    );
-    if (amountError.length === 0) return null;
     let str = "";
+    const apiUrls = getProviderApiUrls();
+    str += `URL - ${location.pathname}\n`;
+    str += `API - ${apiUrls.length > 0}\n\n`;
```
Comment (binaryoverload) [inline src/pages/parts/player/ScrapeErrorPart.tsx:34]: `API - true`?

This just to check that there are API URLs configured?

Comment (mrjvs) [reply src/pages/parts/player/ScrapeErrorPart.tsx:34]: Yea, it's useful since the scraping isn't done in the client when that happens so errors have way different meaning

Comment (binaryoverload) [reply src/pages/parts/player/ScrapeErrorPart.tsx:34]: Gotcha

**Review by binaryoverload — APPROVED** [review]
