### PR TITLE
fix tmdb 404 request

### LINKED ISSUE #1118: [Bug]: TMBD returns 404
### What happened?

TMBD returns 404 even with valid read key
image

### What browsers are you seeing the problem on?

_No response_

### Steps to reproduce?

1.) Download the latest PWA release.
2.) Update the config.js vars.
3.) run with ```python -m http.server 8080```

### Other relevant information

_No response_

### PR DESCRIPTION
**Pull request by JorrinKievit**
This pull request resolves #1118

If the episodes didnt exist (for movies), the isLastEpisode boolean resolves to true, and did a call without a mediaId. Now it does not do the call anymore, and also does no call if the mediaId is not defined.

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

### CODE REVIEW

File: src/components/player/atoms/NextEpisodeButton.tsx [hunk 1]
```diff
@@ -46,10 +46,14 @@ function Button(props: {
...
+function useSeasons(
+  mediaId: string | undefined,
+  isLastEpisode: boolean = false,
+) {
   const state = useAsync(async () => {
     if (isLastEpisode) {
-      const data = await getMetaFromId(MWMediaType.SERIES, mediaId ?? "");
+      if (!mediaId) return;
+      const data = await getMetaFromId(MWMediaType.SERIES, mediaId);
       if (data?.meta.type !== MWMediaType.SERIES) return null;
```
Comment (binaryoverload) [inline src/components/player/atoms/NextEpisodeButton.tsx:57]: Could we make this method either consistently return null or undefined? I seems it does both at the moment

**Review by binaryoverload — CHANGES_REQUESTED** [review]
Looks good!

File: src/components/player/atoms/NextEpisodeButton.tsx (hunk 1 above)
Comment (JorrinKievit) [reply src/components/player/atoms/NextEpisodeButton.tsx]: Yessir

**Review by binaryoverload — APPROVED** [review]
